[general]
import = ["./themes/dracula.toml"]

[font]
size = 13

[font.normal]
family = "Hack Nerd Font Mono"

[font.offset]
y = 6

[[keyboard.bindings]]
action = "ToggleMaximized"
key = "F12"

[mouse]
hide_when_typing = true

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "buttonless"
opacity = 0.96
option_as_alt = "Both"

[window.dimensions]
columns = 128
lines = 32

[window.position]
x = 2096
y = 1440

